module.exports = {
    "claimPaymentEntry": [
        {
            "adjAmount": 0.0,
            "batchNumber": "000000001",
            "cercClaimPaymentCount": 0,
            "cercClaimPaymentStr": "",
            "cercClaimPaymentTotal": 0.0,
            "checkAmount": 1506.85,
            "checkIssueDate": "06/07/2021",
            "checkPayee": "MONTEFIORE MEDICAL CENTER: PO BOX 412508",
            "checkTraceNo": "997982453",
            "claimDetails": [
                {
                    "checkNo": "997982453",
                    "claimNo": "HB171285134600",
                    "claimPaymentDate": null,
                    "claimServiceDate": "05/04/2021-",
                    "nonCoveredCharges": 1588.15,
                    "patientFirstName": "LETICIA",
                    "patientId": "N21954677-01",
                    "patientLastName": "LAPORTE",
                    "patientResp": null,
                    "payment": 1506.85,
                    "provider": "  MOSES HOSPITAL",
                    "providerId": "131740114",
                    "status": "1-Processed as Primary",
                    "system": "HB",
                    "totalCharges": 3095.0
                }
            ],
            "claimPaymentCount": 1,
            "claimPaymentTotal": 1506.85,
            "discrepancyAmt": 0.0,
            "dosaClaimPaymentCount": 0,
            "dosaClaimPaymentStr": "",
            "dosaClaimPaymentTotal": 0.0,
            "eagleClaimPaymentCount": 0,
            "eagleClaimPaymentStr": "",
            "eagleClaimPaymentTotal": 0.0,
            "hb_epicClaimPaymentCount": 1,
            "hb_epicClaimPaymentStr": "HB171285134600,",
            "hb_epicClaimPaymentTotal": 1506.85,
            "hhClaimPaymentCount": 0,
            "hhClaimPaymentTotal": 0.0,
            "hh_epicClaimPaymentCount": 0,
            "hh_epicClaimPaymentStr": "",
            "hh_epicClaimPaymentTotal": 0.0,
            "hhaClaimPaymentStr": "",
            "hsrCapChrgAmt": 0.0,
            "hsrCapPaidAmt": 0.0,
            "idxmocClaimPaymentCount": 0,
            "idxmocClaimPaymentStr": "",
            "idxmocClaimPaymentTotal": 0.0,
            "idxmotClaimPaymentCount": 0,
            "idxmotClaimPaymentStr": "",
            "idxmotClaimPaymentTotal": 0.0,
            "method": "ACH",
            "pb_epicClaimPaymentCount": 0,
            "pb_epicClaimPaymentStr": "",
            "pb_epicClaimPaymentTotal": 0.0,
            "providerAdjustmentPayment": 0.0,
            "providerAdjustmentReasonCode": "",
            "satpClaimPaymentCount": 0,
            "satpClaimPaymentStr": "",
            "satpClaimPaymentTotal": 0.0,
            "ucpClaimPaymentCount": 0,
            "ucpClaimPaymentStr": "",
            "ucpClaimPaymentTotal": 0.0
        },
        {
            "adjAmount": 0.0,
            "batchNumber": "000000001",
            "cercClaimPaymentCount": 0,
            "cercClaimPaymentStr": "",
            "cercClaimPaymentTotal": 0.0,
            "checkAmount": 4023.91,
            "checkIssueDate": "06/07/2021",
            "checkPayee": "MONTEFIORE MEDICAL CENTER: PO BOX 412514",
            "checkTraceNo": "997982454",
            "claimDetails": [
                {
                    "checkNo": "997982454",
                    "claimNo": "P1250110760",
                    "claimPaymentDate": null,
                    "claimServiceDate": "03/31/2021-",
                    "nonCoveredCharges": 11175.82,
                    "patientFirstName": "JENNIFER",
                    "patientId": "E10886794-01",
                    "patientLastName": "MASSEY",
                    "patientResp": null,
                    "payment": 3449.18,
                    "provider": "  JENNY CHOI, MD",
                    "providerId": "131740114",
                    "status": "1-Processed as Primary",
                    "system": "PB",
                    "totalCharges": 14625.0
                },
                {
                    "checkNo": "997982454",
                    "claimNo": "P1248884660",
                    "claimPaymentDate": null,
                    "claimServiceDate": "04/19/2021-",
                    "nonCoveredCharges": 121.05000000000001,
                    "patientFirstName": "ALBERT",
                    "patientId": "E10905811-01",
                    "patientLastName": "GHERARDI",
                    "patientResp": null,
                    "payment": 283.95,
                    "provider": "  BENJAMIN A. ZALTA, MD",
                    "providerId": "131740114",
                    "status": "1-Processed as Primary",
                    "system": "PB",
                    "totalCharges": 405.0
                },
                {
                    "checkNo": "997982454",
                    "claimNo": "P1248884660",
                    "claimPaymentDate": null,
                    "claimServiceDate": "04/19/2021-",
                    "nonCoveredCharges": 405.0,
                    "patientFirstName": "ALBERT",
                    "patientId": "E10905811-01",
                    "patientLastName": "GHERARDI",
                    "patientResp": null,
                    "payment": 0.0,
                    "provider": "  BENJAMIN A. ZALTA, MD",
                    "providerId": "131740114",
                    "status": "1-Processed as Primary",
                    "system": "PB",
                    "totalCharges": 405.0
                },
                {
                    "checkNo": "997982454",
                    "claimNo": "P1252295060",
                    "claimPaymentDate": null,
                    "claimServiceDate": "05/17/2021-",
                    "nonCoveredCharges": 496.56000000000006,
                    "patientFirstName": "DOREA",
                    "patientId": "E10905978-01",
                    "patientLastName": "FERRIS",
                    "patientResp": null,
                    "payment": 290.78,
                    "provider": "  VERONIQUE A. BRINSON, MD",
                    "providerId": "131740114",
                    "status": "1-Processed as Primary",
                    "system": "PB",
                    "totalCharges": 787.34
                },
                {
                    "checkNo": "997982454",
                    "claimNo": "P1245410012",
                    "claimPaymentDate": null,
                    "claimServiceDate": "03/09/2021-",
                    "nonCoveredCharges": 4275.0,
                    "patientFirstName": "AMPARO",
                    "patientId": "15323959C",
                    "patientLastName": "RIVERA",
                    "patientResp": null,
                    "payment": 0.0,
                    "provider": "  ALLAN BROOK, MD",
                    "providerId": "131740114",
                    "status": "1-Processed as Primary",
                    "system": "PB",
                    "totalCharges": 4275.0
                },
                {
                    "checkNo": "997982454",
                    "claimNo": "P1251268780",
                    "claimPaymentDate": null,
                    "claimServiceDate": "07/13/2020-",
                    "nonCoveredCharges": 400.0,
                    "patientFirstName": "VENECIA",
                    "patientId": "17806217C",
                    "patientLastName": "URENA",
                    "patientResp": null,
                    "payment": 0.0,
                    "provider": "  A AMINI HADJIBASHI, MD",
                    "providerId": "131740114",
                    "status": "1-Processed as Primary",
                    "system": "PB",
                    "totalCharges": 400.0
                }
            ],
            "claimPaymentCount": 6,
            "claimPaymentTotal": 4023.91,
            "discrepancyAmt": 0.0,
            "dosaClaimPaymentCount": 0,
            "dosaClaimPaymentStr": "",
            "dosaClaimPaymentTotal": 0.0,
            "eagleClaimPaymentCount": 0,
            "eagleClaimPaymentStr": "",
            "eagleClaimPaymentTotal": 0.0,
            "hb_epicClaimPaymentCount": 0,
            "hb_epicClaimPaymentStr": "",
            "hb_epicClaimPaymentTotal": 0.0,
            "hhClaimPaymentCount": 0,
            "hhClaimPaymentTotal": 0.0,
            "hh_epicClaimPaymentCount": 0,
            "hh_epicClaimPaymentStr": "",
            "hh_epicClaimPaymentTotal": 0.0,
            "hhaClaimPaymentStr": "",
            "hsrCapChrgAmt": 0.0,
            "hsrCapPaidAmt": 0.0,
            "idxmocClaimPaymentCount": 0,
            "idxmocClaimPaymentStr": "",
            "idxmocClaimPaymentTotal": 0.0,
            "idxmotClaimPaymentCount": 0,
            "idxmotClaimPaymentStr": "",
            "idxmotClaimPaymentTotal": 0.0,
            "method": "ACH",
            "pb_epicClaimPaymentCount": 6,
            "pb_epicClaimPaymentStr": "P1250110760,P1248884660,P1248884660,P1252295060,P1245410012,P1251268780,",
            "pb_epicClaimPaymentTotal": 4023.91,
            "providerAdjustmentPayment": 0.0,
            "providerAdjustmentReasonCode": "",
            "satpClaimPaymentCount": 0,
            "satpClaimPaymentStr": "",
            "satpClaimPaymentTotal": 0.0,
            "ucpClaimPaymentCount": 0,
            "ucpClaimPaymentStr": "",
            "ucpClaimPaymentTotal": 0.0
        }
    ],
    "claimPaymentSurchargeEntry": [],
    "fileOwner": "MMC",
    "pLBEntry": [],
    "payerName": "trustmark health benefits",
    "rptDate": "2021-06-03 04:00:00",
    "senderId": null
}
