module.exports = [
    {
        "destination": null,
        "outboundMessageType": "text",
        "outputContent": "SVNBKjAwKiAgICAgICAgICAqMDAqICAgICAgICAgICozMCozNDE4NTgzNzkgICAgICAqMzAqMTMxNzQwMTE0ICAgICAgKjIxMDYwMyowMzQzKl4qMDA1MDEqMDY3NjE3MTU3KjAqUCo6fkdTKkhQKkVDSE9IKjEzMTc0MDExNCoyMDIxMDYwMyowMzQzKjEqWCowMDUwMTBYMjIxQTF+U1QqODM1KjAwMDAwMDAwMX5CUFIqSSoxNTA2Ljg1KkMqQUNIKkNDUCowMSowNDQxMTUxMjYqREEqMDE2Njk1MDg2MTJDKjEzNDE4NTgzNzkqKjAxKjAyMTAwMDMyMipEQSo0ODMwNjU5OTE5MjAqMjAyMTA2MDd+VFJOKjEqOTk3OTgyNDUzKjEzNDE4NTgzNzl+RFRNKjQwNSoyMDIxMDYwMn5OMSpQUipUcnVzdG1hcmsgSGVhbHRoIEJlbmVmaXRzfk4zKlBPIEJveCAyOTIwfk40KkNsaW50b24qSUEqNTI3MzN+UEVSKkNYKkVESSBTVVBQT1JUIFRFQU0qRlgqNDQwODM1NTY1NipURSo0NDA4MzUzNTExflBFUipCTCpFREkgU1VQUE9SVCBURUFNfk4xKlBFKk1PTlRFRklPUkUgTUVESUNBTCBDRU5URVIqWFgqMTk1MjQ3Njk4OH5OMypQTyBCT1ggNDEyNTA4fk40KkJPU1RPTipNQSowMjI0MX5SRUYqVEoqMTMxNzQwMTE0fkxYKjF+Q0xQKkhCMTcxMjg1MTM0NjAwKjEqMzA5NSoxNTA2Ljg1KioxNSowNTIxMjEtMTExLTAyfk5NMSpRQyoxKkxBUE9SVEUqTEVUSUNJQSoqKipNSSpOMjE5NTQ2NzctMDF+Tk0xKjgyKjIqTU9TRVMgSE9TUElUQUwqKioqKkZJKjEzMTc0MDExNH5SRUYqQ0UqQ0lHTkF+RFRNKjIzMioyMDIxMDUwNH5EVE0qMDUwKjIwMjEwNTE0flBFUipDWCoqVEUqODAwNTIxMTU1NX5BTVQqQVUqMTUwNi44NX5TVkMqSEM6ODAwNDgqMTcxKjgzLjI1KioxfkRUTSo0NzIqMjAyMTA1MDR+Q0FTKkNPKjQ1Kjg3Ljc1KjF+UkVGKjZSKkhCMTcxMjg1MTM0NjAwLTF+QU1UKkI2KjgzLjI1flNWQypIQzo4MDA2MSoyOTAqMTQxLjE5KioxfkRUTSo0NzIqMjAyMTA1MDR+Q0FTKkNPKjQ1KjE0OC44MSoxflJFRio2UipIQjE3MTI4NTEzNDYwMC0yfkFNVCpCNioxNDEuMTl+U1ZDKkhDOjgyNjcwKjUyMCoyNTMuMTcqKjF+RFRNKjQ3MioyMDIxMDUwNH5DQVMqQ08qNDUqMjY2LjgzKjF+UkVGKjZSKkhCMTcxMjg1MTM0NjAwLTN+QU1UKkI2KjI1My4xN35TVkMqSEM6ODMwMDEqMzU0KjE3Mi4zNSoqMX5EVE0qNDcyKjIwMjEwNTA0fkNBUypDTyo0NSoxODEuNjUqMX5SRUYqNlIqSEIxNzEyODUxMzQ2MDAtNH5BTVQqQjYqMTcyLjM1flNWQypIQzo4MzAzNioyMjYqMTEwLjAzKioxfkRUTSo0NzIqMjAyMTA1MDR+Q0FTKkNPKjQ1KjExNS45NyoxflJFRio2UipIQjE3MTI4NTEzNDYwMC01fkFNVCpCNioxMTAuMDN+U1ZDKkhDOjgzNTQwKjEzMCo2My4yOSoqMX5EVE0qNDcyKjIwMjEwNTA0fkNBUypDTyo0NSo2Ni43MSoxflJFRio2UipIQjE3MTI4NTEzNDYwMC02fkFNVCpCNio2My4yOX5TVkMqSEM6ODQ0MzkqMzM1KjE2My4xKioxfkRUTSo0NzIqMjAyMTA1MDR+Q0FTKkNPKjQ1KjE3MS45KjF+UkVGKjZSKkhCMTcxMjg1MTM0NjAwLTd+QU1UKkI2KjE2My4xflNWQypIQzo4NDQ0MyozNDAqMTY1LjUzKioxfkRUTSo0NzIqMjAyMTA1MDR+Q0FTKkNPKjQ1KjE3NC40NyoxflJFRio2UipIQjE3MTI4NTEzNDYwMC04fkFNVCpCNioxNjUuNTN+U1ZDKkhDOjg0NDY2KjMwNioxNDguOTgqKjF+RFRNKjQ3MioyMDIxMDUwNH5DQVMqQ08qNDUqMTU3LjAyKjF+UkVGKjZSKkhCMTcxMjg1MTM0NjAwLTl+QU1UKkI2KjE0OC45OH5TVkMqSEM6ODQ0ODAqMzIyKjE1Ni43NyoqMX5EVE0qNDcyKjIwMjEwNTA0fkNBUypDTyo0NSoxNjUuMjMqMX5SRUYqNlIqSEIxNzEyODUxMzQ2MDAtMTB+QU1UKkI2KjE1Ni43N35TVkMqSEM6ODUwMjUqMTAxKjQ5LjE5KioxfkRUTSo0NzIqMjAyMTA1MDR+Q0FTKkNPKjQ1KjUxLjgxKjF+UkVGKjZSKkhCMTcxMjg1MTM0NjAwLTExfkFNVCpCNio0OS4xOX5TRSo3OCowMDAwMDAwMDF+R0UqMSoxfklFQSoxKjA2NzYxNzE1N34=",
        "outputProperties": {
            "ProfileId": ".SPLIT.HB_EPIC",
            "SplitKey": "HB_EPIC",
            "AddKey": "DOSA,SATP",
            "PreSplitFilename": "Echo-Generic.20210610215540.combined.835",
            "ISA_DATE": "210603",
            "OrigFilename": "Echo-Generic.20210610215540.combined.835.SPLIT.HB_EPIC_1_of_7",
            "TransType": "835",
            "OrigIsaUnitCount": "7",
            "SplitIsaUnitCount": "1",
            "ISA_TIME": "0343",
            "SplitFilename": "Echo-Generic.20210610215540.combined.835.SPLIT.HB_EPIC_1_of_7"
        },
        "outputPropertyNames": [
            "TransType",
            "SplitIsaUnitCount",
            "ProfileId",
            "OrigFilename",
            "SplitKey",
            "ISA_TIME",
            "PreSplitFilename",
            "OrigIsaUnitCount",
            "ISA_DATE",
            "SplitFilename",
            "AddKey"
        ]
    },
    {
        "destination": null,
        "outboundMessageType": "text",
        "outputContent": "SVNBKjAwKiAgICAgICAgICAqMDAqICAgICAgICAgICozMCozNDE4NTgzNzkgICAgICAqMzAqMTMxNzQwMTE0ICAgICAgKjIxMDYwMyowMzQzKl4qMDA1MDEqMDY3NjE3MTU3KjAqUCo6fkdTKkhQKkVDSE9IKjEzMTc0MDExNCoyMDIxMDYwMyowMzQzKjEwMDAqWCowMDUwMTBYMjIxQTF+U1QqODM1KjAwMDAwMDAwMX5CUFIqSSo0MDIzLjkxKkMqQUNIKkNDUCowMSowNDQxMTUxMjYqREEqMDE2Njk1MDg2MTJDKjEzNDE4NTgzNzkqKjAxKjAyMTAwMDMyMipEQSo0ODMwNjU5OTE5MjAqMjAyMTA2MDd+VFJOKjEqOTk3OTgyNDU0KjEzNDE4NTgzNzl+RFRNKjQwNSoyMDIxMDYwMn5OMSpQUipUcnVzdG1hcmsgSGVhbHRoIEJlbmVmaXRzfk4zKlBPIEJveCAyOTIwfk40KkNsaW50b24qSUEqNTI3MzN+UEVSKkNYKkVESSBTVVBQT1JUIFRFQU0qRlgqNDQwODM1NTY1NipURSo0NDA4MzUzNTExflBFUipCTCpFREkgU1VQUE9SVCBURUFNfk4xKlBFKk1PTlRFRklPUkUgTUVESUNBTCBDRU5URVIqWFgqMTA2MzUyNTE1Mn5OMypQTyBCT1ggNDEyNTE0fk40KkJPU1RPTipNQSowMjI0MX5SRUYqVEoqMTMxNzQwMTE0fkxYKjF+Q0xQKlAxMjUwMTEwNzYwKjEqMTQ2MjUqMzQ0OS4xOCozODMuMjQqMTUqMDUxNjIxLTExMy00MH5OTTEqUUMqMSpNQVNTRVkqSkVOTklGRVIqKioqTUkqRTEwODg2Nzk0LTAxfk5NMSo4MioyKkpFTk5ZIENIT0ksIE1EKioqKipGSSoxMzE3NDAxMTR+UkVGKkNFKk1QIFBIWVNJQ0lBTi9BTkNJTExBfkRUTSoyMzIqMjAyMTAzMzF+RFRNKjA1MCoyMDIxMDUxM35QRVIqQ1gqKlRFKjg3NzQ5ODg5Mzd+QU1UKkFVKjM4MzIuNDJ+U1ZDKkhDOjQzNzc1KjE0NjI1KjM0NDkuMTgqKjF+RFRNKjQ3MioyMDIxMDMzMX5DQVMqQ08qNDUqMTA3OTIuNTgqMX5DQVMqUFIqMiozODMuMjQqMX5SRUYqNlIqMX5BTVQqQjYqMzgzMi40Mn5DTFAqUDEyNDg4ODQ2NjAqMSo0MDUqMjgzLjk1KioxNSowNTIxMjEtMTc5LTgzfk5NMSpRQyoxKkdIRVJBUkRJKkFMQkVSVCoqKipNSSpFMTA5MDU4MTEtMDF+Tk0xKklMKjEqR0hFUkFSREkqUk9TRU1BUklFKioqKk1JKkUxMDkwNTgxMS0wMX5OTTEqODIqMipCRU5KQU1JTiBBLiBaQUxUQSwgTUQqKioqKkZJKjEzMTc0MDExNH5SRUYqQ0UqQ0lHTkF+RFRNKjIzMioyMDIxMDQxOX5EVE0qMDUwKjIwMjEwNTIwflBFUipDWCoqVEUqODc3NDk4ODkzN35BTVQqQVUqMjgzLjk1flNWQypIQzo3MTI1MDoyNio0MDUqMjgzLjk1KioxfkRUTSo0NzIqMjAyMTA0MTl+Q0FTKkNPKjQ1KjEyMS4wNSoxflJFRio2UioxfkFNVCpCNioyODMuOTV+Q0xQKlAxMjQ4ODg0NjYwKjEqNDA1KjAqKjE1KjA1MjEyMS0xODAtMDZ+Tk0xKlFDKjEqR0hFUkFSREkqQUxCRVJUKioqKk1JKkUxMDkwNTgxMS0wMX5OTTEqSUwqMSpHSEVSQVJESSpST1NFTUFSSUUqKioqTUkqRTEwOTA1ODExLTAxfk5NMSo4MioyKkJFTkpBTUlOIEEuIFpBTFRBLCBNRCoqKioqRkkqMTMxNzQwMTE0flJFRipDRSpDSUdOQX5EVE0qMjMyKjIwMjEwNDE5fkRUTSowNTAqMjAyMTA1MjB+UEVSKkNYKipURSo4Nzc0OTg4OTM3flNWQypIQzo3MTI1MDoyNio0MDUqMCoqMX5EVE0qNDcyKjIwMjEwNDE5fkNBUypDTyo0NSoxMjEuMDUqMX5DQVMqT0EqMTgqMjgzLjk1KjF+UkVGKjZSKjF+TFEqSEUqTjExMX5DTFAqUDEyNTIyOTUwNjAqMSo3ODcuMzQqMjkwLjc4KioxNSowNTI0MjEtMzcwLTU0fk5NMSpRQyoxKkZFUlJJUypET1JFQSpBKioqTUkqRTEwOTA1OTc4LTAxfk5NMSo4MioyKlZFUk9OSVFVRSBBLiBCUklOU09OLCBNRCoqKioqRkkqMTMxNzQwMTE0flJFRipDRSpDSUdOQX5EVE0qMjMyKjIwMjEwNTE3fkRUTSowNTAqMjAyMTA1MjR+UEVSKkNYKipURSo4Nzc0OTg4OTM3fkFNVCpBVSoyOTAuNzh+U1ZDKkhDOjkwNDcxKjExMCoxMDkuMzMqKjF+RFRNKjQ3MioyMDIxMDUxN35DQVMqQ08qNDUqMC42NyoxflJFRio2UipQMTI1MjI5NTA2MC0xfkFNVCpCNioxMDkuMzN+U1ZDKkhDOjkwNzUwKjY3Ny4zNCoxODEuNDUqKjF+RFRNKjQ3MioyMDIxMDUxN35DQVMqQ08qNDUqNDk1Ljg5KjF+UkVGKjZSKlAxMjUyMjk1MDYwLTJ+QU1UKkI2KjE4MS40NX5DTFAqUDEyNDU0MTAwMTIqMSo0Mjc1KjAqKjE1KjA1MzAyMS0xMDgtMjF+Tk0xKlFDKjEqUklWRVJBKkFNUEFSTyoqKipNSSoxNTMyMzk1OUN+Tk0xKjgyKjIqQUxMQU4gQlJPT0ssIE1EKioqKipGSSoxMzE3NDAxMTR+UkVGKkNFKk1FRElDQVJFL01FRElDQUlEfkRUTSoyMzIqMjAyMTAzMDl+RFRNKjA1MCoyMDIxMDUyN35QRVIqQ1gqKlRFKjg1NTgzMTkyMjd+U1ZDKkhDOjIyNTEzKjQyNzUqMCoqMX5EVE0qNDcyKjIwMjEwMzA5fkNBUypDTyo0NSozNjA5Ljc4KjF+Q0FTKk9BKjE4KjY2NS4yMioxflJFRio2UioxfkxRKkhFKk4xMTF+Q0xQKlAxMjUxMjY4NzgwKjEqNDAwKjAqKjE1KjA1MjcyMS0xNTAtNTd+Tk0xKlFDKjEqVVJFTkEqVkVORUNJQSoqKipNSSoxNzgwNjIxN0N+Tk0xKjgyKjIqQSBBTUlOSSBIQURKSUJBU0hJLCBNRCoqKioqRkkqMTMxNzQwMTE0flJFRipDRSpNRURJQ0FSRS9NRURJQ0FJRH5EVE0qMjMyKjIwMjAwNzEzfkRUTSowNTAqMjAyMTA1MjZ+UEVSKkNYKipURSo4NTU4MzE5MjI3flNWQypIQzo5OTIxMyo0MDAqMCoqMX5EVE0qNDcyKjIwMjAwNzEzfkNBUypPQSoyMjYqNDAwKjF+UkVGKjZSKlAxMjUxMjY4NzgwLTF+TFEqSEUqTUEwNH5MUSpIRSpONH5TRSoxMDEqMDAwMDAwMDAxfkdFKjEqMTAwMH5JRUEqMSowNjc2MTcxNTd+",
        "outputProperties": {
            "ProfileId": ".SPLIT.PB_EPIC",
            "SplitKey": "PB_EPIC",
            "AddKey": "DOSA,SATP",
            "PreSplitFilename": "Echo-Generic.20210610215540.combined.835",
            "ISA_DATE": "210603",
            "OrigFilename": "Echo-Generic.20210610215540.combined.835.SPLIT.PB_EPIC_6_of_7",
            "TransType": "835",
            "OrigIsaUnitCount": "7",
            "SplitIsaUnitCount": "6",
            "ISA_TIME": "0343",
            "SplitFilename": "Echo-Generic.20210610215540.combined.835.SPLIT.PB_EPIC_6_of_7"
        },
        "outputPropertyNames": [
            "TransType",
            "SplitIsaUnitCount",
            "ProfileId",
            "OrigFilename",
            "SplitKey",
            "ISA_TIME",
            "PreSplitFilename",
            "OrigIsaUnitCount",
            "ISA_DATE",
            "SplitFilename",
            "AddKey"
        ]
    }
]
