module.exports = [
    "",
    "1199SEIU",
    "AARP Supplementa",
    "ACS STATE HEALTH",
    "AETNA  INC",
    "AETNA A04",
    "AETNA AS01",
    "AETNA GENWORTH",
    "AETNA H09",
    "AETNA LIFE INSUR",
    "AETNA SSI",
    "AMERICAN HOME AS",
    "AMERICAN PROGRES",
    "Amerigroup GA5C",
    "Amerigroup MD5C",
    "Amerigroup NJ5C",
    "Amerigroup TX5C",
    "AMETROS FINANCIA",
    "Amida Care Inc.",
    "ANTHEM BLUE 05C",
    "ANTHEM BLUE CO5C",
    "ANTHEM BLUE CT5C",
    "ANTHEM BLUE IN5C",
    "ANTHEM BLUE KY5C",
    "ANTHEM BLUE ME5C",
    "ANTHEM BLUE NV5C",
    "ANTHEM BLUE VA5C",
    "APWU HP HO PMT",
    "ARCHCARE ADVANTA",
    "ARCHCARE SENIOR",
    "Banner Health Nt",
    "BCBSAL CROSS R",
    "BEACON HEALTH",
    "BLUE CROSS CA5C",
    "BLUE CROSS GA5C",
    "Bricklayers & Al",
    "CAQH",
    "Cedar Cares Inc.",
    "CenterLight Heal",
    "CFHNYC",
    "CIGNA",
    "CIGNA EDGE TRANS",
    "CIGNA GLOBAL INS",
    "CIGNA HLTH LIFE",
    "CIGNA LIFE OF CA",
    "Cigna-HealthSpri",
    "CLOVER INSURANCE",
    "CMMI QPP NGS",
    "CMMI QPP NGS Acc",
    "COLLEGE ST ROSE",
    "COMM OF MASS",
    "COMMERCE BANK",
    "CONTINENTAL LIFE",
    "COVID19 HRSA",
    "CSRA DHB PAYMENT",
    "DEAN HEALTH PLAN",
    "DENTAQUEST IPA O",
    "DHHS CSRA DPH",
    "EH FACET EFT",
    "EH FIDA EFT",
    "ELDERPLAN",
    "ELDERSERVE HEALT",
    "Ellis Hospital",
    "EMPIRE BLUE 05A",
    "EMPIRE BLUE 05C",
    "EMPIRE BLUE 05F",
    "EPC TRUST",
    "Erie Insurance C",
    "Erie Insurance G",
    "Erie Insurance P",
    "FIDELIS CARE",
    "FIRST UNITED AME",
    "GEHA",
    "GHI FACETS",
    "GHI FED EPO",
    "GHI FED FACETS",
    "GHI FED HDHP EFT",
    "GHI FED PPO",
    "GHI NYC EFT",
    "GHI NYC FACETS",
    "GOLDCARE I",
    "GOLDCARE II",
    "GROUP HEALTH",
    "Guardian Life In",
    "HDIC",
    "HEALTH EZ",
    "HEALTHFIRST HEAL",
    "HEALTHFIRST HFIC",
    "HEALTHFIRST PHSP",
    "HEALTHFIRST SHP",
    "HEHP GA",
    "HERITAGE HEALTH",
    "HFAP",
    "HFHP HF",
    "HHP",
    "HHP LOU",
    "HIC NY",
    "HIMINSPR",
    "HIP OF GR NY",
    "HMP",
    "HNB - ECHO",
    "HUDSON VALLEY IP",
    "HUMANA AHP",
    "HUMANA AHPNY",
    "HUMANA CHA DISB",
    "HUMANA GOVT BUSI",
    "HUMANA HEALTH PL",
    "HUMANA HIC",
    "HUMANA INS CO",
    "HWHO",
    "ILLINOIS NATIONA",
    "INDEPENDENT HEAL",
    "Integris",
    "MAGNACARE600000",
    "MAGNACARE701021",
    "MAGNACARE701808",
    "MAGNACARE701859",
    "MAGNACARE701934",
    "MAGNACARE702214",
    "MAGNACARE702227",
    "MAGNACARE702430",
    "MAGNACARE703028",
    "MAGNACARE703034",
    "MAGNACARE703046",
    "MAGNACARE703131",
    "MAGNACARE703382",
    "MAGNACARE703383",
    "MAGNACARE703521",
    "MAGNACARE703708",
    "MAGNACARE703814",
    "MAGNACARE704104",
    "MANAGED HEALTH",
    "MAYO MEDICAL  PL",
    "McLaren Medicaid",
    "Medica",
    "MET LIFE INS. CO",
    "METROPLUS ENHANC",
    "METROPLUS ESSENT",
    "METROPLUS EXCHAN",
    "METROPLUS HEALTH",
    "METROPLUS PARTNE",
    "MONTEFIORE HMO L",
    "MUTUAL OF OMAHA",
    "MVP Health Plan",
    "MVP Health Plan,",
    "NALCHBP GROUP",
    "NATIONAL GOVERNM",
    "Nationwide",
    "NEW HAMPSHIRE IN",
    "NGS, INC.",
    "NY44 Health Bene",
    "NYS DOH",
    "NYU Grossman SOM",
    "OMAHA INS CO",
    "OPERATING ACCOUN",
    "Optum VA CCN Reg",
    "OXFORD HEA PL CT",
    "OXFORD HEA PL LL",
    "OXFORD HEA PL NY",
    "OXFORD HEALTH IN",
    "OXFORD HEALTH PL",
    "PALMETTO GBA",
    "PAY PLUS",
    "Peckham Industri",
    "PHYSICIANHEAHH",
    "PNC-ECHO",
    "PREFERRED MED CL",
    "Qualcare",
    "Rally Pay Member",
    "SENIOR WHOLE HEA",
    "Simply FL5C",
    "SISTERS OF MERCY",
    "SNJ-MED.ASST.PAY",
    "Spectera EyeCare",
    "ST OF CONN D.S.S",
    "STUDENT RESOURCE",
    "Teamsters Local",
    "The Arc Mid-Huds",
    "THE HARTFORD",
    "THE MONTEFIORE I",
    "THRIVENT FINANCI",
    "Transamerica Fin",
    "Transamerica Lif",
    "Transamerica Pre",
    "TRIWEST HEALTHCA",
    "Tufts Health Pub",
    "UHC Benefits Pla",
    "UHC COMMUNITY PL",
    "UHC DUAL COMPLET",
    "UHC GOVERNMENT E",
    "UHC HARVARD PILG",
    "UHC Insurance Co",
    "UHC MASHANTUCKET",
    "UHC Member Payme",
    "UHC OF FL DUAL",
    "UHC OF LOUISIANA",
    "UHC OF NEW ENGLA",
    "UHC OF THE MIDAT",
    "UHC THE FLORIDA",
    "UHIC",
    "UHS SACM",
    "UMR",
    "UMR ABB CONCISE",
    "UMR ACTIVE MEDIA",
    "UMR ALSTON BIRD",
    "UMR AMERICAN MED",
    "UMR BMO HARRIS B",
    "UMR CENTRAL FLOR",
    "UMR CITY OF PEMB",
    "UMR CUMBERLAND P",
    "UMR DALLAS COUNT",
    "UMR DAV",
    "UMR DSW INC",
    "UMR EATON CORPOR",
    "UMR ELLANEF MANU",
    "UMR EVERGREEN SH",
    "UMR EXTRA SPACE",
    "UMR G III LEATHE",
    "UMR INFOGROUP IN",
    "UMR ISUZU MOTORS",
    "UMR JOHN HANCOCK",
    "UMR LOST ARROW C",
    "UMR LUTHERAN SOC",
    "UMR MACKAY COMMU",
    "UMR MAVIS TIRE S",
    "UMR NATIONAL CAR",
    "UMR NELSON TREE",
    "UMR NEXSTAR BROA",
    "UMR PENTON LEARN",
    "UMR PRATT INSTIT",
    "UMR QBE THE AMER",
    "UMR SOLOMON PAGE",
    "UMR STANLEY STEE",
    "UMR THE METROPOL",
    "UMR TRUMP PAYROL",
    "UMR U S VENTURE",
    "UMR UNIVERSITY O",
    "UMR USNAS",
    "UMR WESTMED MEDI",
    "UMR WORLD WIDE T",
    "UMR YOUNG LIFE",
    "UNICARE 05C",
    "UNITED AMERICAN",
    "UNITED BEHAVIORA",
    "United HealthCar",
    "UNITED OF OMAHA",
    "UnitedHealthcare",
    "University of Ma",
    "ValueOptions",
    "VALUEOPTIONSA11",
    "VALUEOPTIONSEH7",
    "VALUEOPTIONSEH8",
    "VISITING NURSE S",
    "VNS CHOICE",
    "VNSNY CHOICE SEL",
    "WellCare Health",
    "WELLCARE OF FLOR",
    "WELLCARE OF NEW",
    "WELLCARECTCARE",
    "WELLCAREFLCAID",
    "WELLCAREFLCARE",
    "WELLCAREGACAID",
    "WELLCAREGACARE",
    "WELLCARENEWJERSE",
    "WELLCARENYCAID",
    "WELLCARENYCARE",
    "WISCONSIN PHYSIC",
    "ZELIS PAYMENTS"
]
