[
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.1199.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.1199.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.1199.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 24~PayerName=1199~SenderId=131628401~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup 1199 BPR report trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.AETNA.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.AETNA.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.AETNA.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 23~PayerName=AETNA~SenderId=042064683~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup Aetna BPR report trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.AETNAEDI.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.AETNAEDI.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.AETNAEDI.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleAetna835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR Aetna 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB-EPIC",
        "processSender": "AETNA",
        "processTransType": "835",
        "stepMask": "1,3,13",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.AETNAEDI.835.COMBTRIG.TEST",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.AETNAEDI.835.TEST",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.AETNAEDI.835.COMBTRIG.TEST",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleAetna835StagingTest~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR Aetna 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB-EPIC",
        "processSender": "AETNA",
        "processTransType": "835",
        "stepMask": "1,3,13",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.AFFINITY.ECHO.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.AFFINITY.835.ECHO",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.AFFINITY.ECHO.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleAffinityEcho835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR Affinity Echo 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Affinity-Echo",
        "processTransType": "835",
        "stepMask": "1,4,5",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.AMERIGROUP.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.AMERIGROUP.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.AMERIGROUP.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleAmerigroup835Staging~ISA06=AMERIGROUP~ISA08=MONTEFIORE~GS02=AMERIGROUP~GS03=PROVIDERHIS~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR Amerigroup 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB-EPIC",
        "processSender": "Amerigroup",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.AMERIGROUP.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.AMERIGROUP.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.AMERIGROUP.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 24~PayerName=Amerigroup~SenderId=AMERIGROUP~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup Amerigroup BPR trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.BC.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.BC.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.BC.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleBlueCross835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR Blue Cross 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "BlueCross",
        "processTransType": "835",
        "stepMask": "1,2,3,5",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.BCBS.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.BCBS.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.BCBS.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 24~PayerName=EmpireBCBS~SenderId=EMPIRENY~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup BCBS BPR report trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.FIDELIS.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.FIDELIS.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.FIDELIS.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 24~PayerName=Fidelis~SenderId=113153422~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup BPR Report trigger for Fidelis",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.AFFINITY.ECHO.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.AFFINITY.835.ECHO",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.GENERIC.ECHO.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch1/edidev/MMC-Staging/EchoGeneric835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR Affinity Echo 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Echo-Generic",
        "processTransType": "835",
        "stepMask": "1,4,5",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.GHI.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.GHI-PNC.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.GHI-PNC.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleGHI835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR GHI 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB-EPIC",
        "processSender": "GHI-PNC",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.HIPGHIHMO.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.HIPGHIHMO.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.HIPGHIHMO.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleHIP835Staging~ISA06=FISACURE3~ISA08=00IDI~GS02=FISACURE3~GS03=00IDI~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR HIP 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "HIP",
        "processTransType": "835",
        "stepMask": "1,2,3,5",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.MCRA.835.COMBTRIG",
        "deliveryMode": "SFTP",
        "deliveryProfile": "EAGLE.DELIVER.MCRA.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.MCRA.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleMCRA835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR MCRA 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB-EPIC",
        "processSender": "MedicareA",
        "processTransType": "835",
        "stepMask": "1,2,3",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.MCRB.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.MCRB.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.MCRB.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleMCRB835Staging~AlertOnZeroFiles=N",
        "pollControlDescr": "Pickup HSR MCRB 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HSR",
        "processSender": "MedicareB",
        "processTransType": "835",
        "stepMask": "1,2,3",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.MCRB.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.MCRB.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.MCRB.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 24~PayerName=Medicare Part B~SenderId=13202~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup Medicare part B BPR report trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.METROPLUS.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.METROPLUS.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.METROPLUS.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleMetroplus835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup HSR Metroplus 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB-EPIC",
        "processSender": "Metroplus",
        "processTransType": "835",
        "stepMask": "1,2,3,5",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.METROPLUS.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.METROPLUS.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.METROPLUS.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 144~PayerName=Metroplus~SenderId=INSTAMED~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup BPR Report trigger for Metroplus",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.NHP.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.NHP.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.NHP.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleNHP835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup EAGLE NHP 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HSR",
        "processSender": "NHP",
        "processTransType": "835",
        "stepMask": "1,2,3,5",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.NHP.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.NHP.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.NHP.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 48~PayerName=NHP~SenderId=NEIGHBORHOOD HP~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup NHP (Neighborhood Health Providers) BPR report trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.OXFORD.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.OXFORD.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.OXFORD.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 24~PayerName=Oxford~SenderId=043000096835~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup OXFORD BPR report trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.UHC.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.UHC.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.UHC.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 24~PayerName=UHC~SenderId=United Healthca~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup UHC BPR report trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "EAGLE.PICKUP.WELLCARE.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.WELLCARE.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.WELLCARE.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/EagleWellcare835Staging~ISA06=WELLCARE~ISA08=MONTEFIORE~GS02=WELLCARE~GS03=PROVIDERHIS~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Wellcare 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB-EPIC",
        "processSender": "Wellcare",
        "processTransType": "835",
        "stepMask": "1,4",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "EAGLE.PICKUP.WELLCARE.BPR.TRIG",
        "deliveryMode": "FTP",
        "deliveryProfile": "EAGLE.DELIVER.WELLCARE.BPR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "EAGLE.PICKUP.WELLCARE.BPR.TRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "QueryEnd=0 and 24~PayerName=Wellcare~SenderId=WELLCARE~RouteList=hsrReport.BprReportSummary",
        "pollControlDescr": "Pickup BPR Report trigger for Wellcare",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "DHUB",
        "processSender": "HSR",
        "processTransType": "BPR",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "HB_EPIC.PICKUP.AFFINITY.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "HB_EPIC.DELIVER.AFFINITY.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "HB_EPIC.PICKUP.AFFINITY.INSTAMED.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/HBAffinity835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Affinity 835 from Instamed for HB_EPIC",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Affinity-Instamed",
        "processTransType": "835",
        "stepMask": "1,4,13",
        "stepNo": "1",
        "systemId": "HB-EPIC"
    },
    {
        "activeFlag": "N",
        "configId": "JZANUS.PICKUP.NOTES.COMTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "JZANUS.DELIVER.NOTES",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "JZANUS.PICKUP.NOTES.COMTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=genericxlat.ConcatenateFiles~ProfileId=JZANUS.DELIVER.NOTES~BaseDir=/edibatch/ediprod/MMC-Staging/JzanusStaging",
        "pollControlDescr": "Pickup trigger file for Jzanus combination process",
        "pollLogs": null,
        "processName": "JZANUS Notes",
        "processReceiver": "CBR",
        "processSender": "JZANUS",
        "processTransType": "Notes",
        "stepMask": null,
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "MMC.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "EAGLE.DELIVER.HF.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MMC835Staging~",
        "pollControlDescr": "Pickup ANY 835 Combine Trigger",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Emblem",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": "1",
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.OXFORD.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.TEST.SPLIT835.CBR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.835.COMBTRIG.TEST",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch1/edidev/MMC-Staging/MmcTest835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Oxford 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Test",
        "processTransType": "835",
        "stepMask": "1,4,13",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.AMERIGROUP-BOA.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.AMERIGROUP-BOA.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcpayspanamerigroupboaStaging~AlertOnZeroFiles=Y~PayerName=Amerigroup",
        "pollControlDescr": "Pickup payspan 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "PAYSPAN-AMERIGROUP",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.AMIDA.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.AMIDA.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.AMIDA.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MMCAmida835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup AMIDA 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "AMIDA",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.APWU.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.APWU-PNC.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MMCAPWU835Staging~AlertOnZeroFiles=Y~PayerName=APWU",
        "pollControlDescr": "Pickup HSR GHI 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "APWU-PNC",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.BEACON-BOA.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.BEACON-BOA.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcpayspanbeaconboaStaging~AlertOnZeroFiles=Y~PayerName=Beacon",
        "pollControlDescr": "Pickup payspan 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "PAYSPAN-BEACON",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.BEACON.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.BEACON.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.BEACON.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MMCBeacon835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Beacon 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Beacon",
        "processTransType": "835",
        "stepMask": "1,2,3",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.CENTERLIGHT.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.CENTERLIGHT.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.CENTERLIGHT.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MMCCenterlightStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Centerlight 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Centerlight",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.CIGNA.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.COMBINED.CIGNA.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.CIGNA.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcCignaStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup CIGNA 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "CIGNA",
        "processTransType": "835",
        "stepMask": "1,3,13",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.CMO.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.CMO.SPLIT835.CBR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.CMO.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcCMOStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Combine Trigger for CMO 835 (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "CMO",
        "processTransType": "835",
        "stepMask": "1,4,13",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.ELDERSERVE-BOA.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.ELDERSERVE-BOA.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcpayspanelderserveboaStaging~AlertOnZeroFiles=Y~PayerName=Elderserve",
        "pollControlDescr": "Pickup payspan 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "PAYSPAN-ELDERSERVE",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "N",
        "configId": "MMC.PICKUP.EMBLEM.ECHO.835.COMBTRIG",
        "deliveryMode": "SFTP",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.EMBLEM.ECHO.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch1/ediprod/MMC-Staging/MMCEchoEmblemStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Emblem Echo 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Echo-Emblem",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "N",
        "configId": "MMC.PICKUP.EMBLEMFACETS.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.EMBLEMFACETS.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.EMBLEMFACETS.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MMCEmblemFacetsStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Emblem FACETS 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "EmblemFacets",
        "processTransType": "835",
        "stepMask": "1,2,3,5",
        "stepNo": null,
        "systemId": "EAGLE"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.FIDELIS.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.FIDELIS.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcFidelisAvaility~AlertOnZeroFiles=Y~PayerName=Fidelis",
        "pollControlDescr": "Pickup Fidelis 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Fidelis-Availity",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.MAGNACARE.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.MAGNACARE.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.MAGNACARE.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MMCMAGNACAREStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Magnacare 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Magnacare",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.MVP-BOA.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.MVP-BOA.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcpayspanmvpboaStaging~AlertOnZeroFiles=Y~PayerName=MVP",
        "pollControlDescr": "Pickup payspan 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "PAYSPAN-MVP",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.NALC.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.NALC.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MMCNALC835Staging~AlertOnZeroFiles=Y~PayerName=Beacon",
        "pollControlDescr": "Pickup payspan 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "NALC",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.OXFORD.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.OXFORD.SPLIT835.CBR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.OXFORD.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch1/edidev/MMC-Staging/MmcOxfordStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Oxford 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "OXFORD",
        "processTransType": "835",
        "stepMask": "1,4,13",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.UHC.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.UHC.SPLIT835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.UHC.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcUhcStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup UHC 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "UHC",
        "processTransType": "835",
        "stepMask": "1,4,13",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.VNS.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.VNS.835.CBR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.VNS.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcVnsStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup MMC VNS 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB_EPIC",
        "processSender": "VNS",
        "processTransType": "835",
        "stepMask": "1,2,3",
        "stepNo": "1",
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.WELLCARE-BOA.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.PAYSPAN.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.WELLCARE-BOA.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcpayspanwellcareboaStaging~AlertOnZeroFiles=Y~PayerName=Wellcare",
        "pollControlDescr": "Pickup payspan 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "PAYSPAN-WELLCARE",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MMC.PICKUP.ZELIS.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.ZELIS.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MMC.PICKUP.ZELIS.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MmcZelisStaging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup Zelis 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Zelis",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MMC"
    },
    {
        "activeFlag": "Y",
        "configId": "MOT.PICKUP.AMERIGROUP.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MOT.DELIVER.AMERIGROUP.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MOT.PICKUP.AMERIGROUP.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~GS02=AMERIGROUP~SendOrigFile=N~StagingDir=/edibatch/ediprod/MMC-Staging/MotAmerigroup835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup MOT Amerigroup 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "PB-EPIC",
        "processSender": "Amerigroup",
        "processTransType": "835",
        "stepMask": "1,7,8",
        "stepNo": null,
        "systemId": "MOT"
    },
    {
        "activeFlag": "Y",
        "configId": "MOT.PICKUP.BS.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MOT.DELIVER.BS.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MOT.PICKUP.BS.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MotBlueShield835Staging~ISA06=EMPIRENY~GS02=EMPIRENY~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup MOT Blue Shield 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "PB-EPIC",
        "processSender": "Blue Shield",
        "processTransType": "835",
        "stepMask": "1,7,8",
        "stepNo": null,
        "systemId": "MOT"
    },
    {
        "activeFlag": "N",
        "configId": "MOT.PICKUP.NHP.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MOT.DELIVER.NHP.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MOT.PICKUP.NHP.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MotNHP835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup MOT NHP 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "FPP",
        "processSender": "NHP",
        "processTransType": "835",
        "stepMask": null,
        "stepNo": null,
        "systemId": "MOT"
    },
    {
        "activeFlag": "Y",
        "configId": "MOT.PICKUP.VNS.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MMC.DELIVER.VNS.835.CBR",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MOT.PICKUP.VNS.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MotVNS835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup MOT VNS 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "PB_EPIC",
        "processSender": "VNS",
        "processTransType": "835",
        "stepMask": "1,14,8",
        "stepNo": "1",
        "systemId": "MOT"
    },
    {
        "activeFlag": "Y",
        "configId": "MOT.PICKUP.WELLCARE.835.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "MOT.DELIVER.WELLCARE.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "MOT.PICKUP.WELLCARE.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/MotWellcare835Staging~ISA06=WELLCARE~ISA08=PAYER~GS02=WELLCARE~GS03=PAYER~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup MOT Wellcare 835 Combine Trigger (NOT the 835)",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "PB-EPIC",
        "processSender": "Wellcare",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": null,
        "systemId": "MOT"
    },
    {
        "activeFlag": "Y",
        "configId": "PB_EPIC.PICKUP.AFFINITY.COMBTRIG",
        "deliveryMode": "LOCALFILE",
        "deliveryProfile": "HB_EPIC.DELIVER.AFFINITY.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "PB_EPIC.PICKUP.AFFINITY.835.COMBTRIG",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/ediprod/MMC-Staging/Affinity835Staging~AlertOnZeroFiles=Y",
        "pollControlDescr": "Pickup EPIC 835 from Affinity via Instamed",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "MMC",
        "processSender": "Affinity-Instamed",
        "processTransType": "835",
        "stepMask": "1,14",
        "stepNo": "1",
        "systemId": "EPIC"
    },
    {
        "activeFlag": "N",
        "configId": "TEMP.TEST.PICKUP.835.4COMBINE",
        "deliveryMode": "SFTP",
        "deliveryProfile": "EAGLE.DELIVER.TEST.835",
        "id": {
            "facilityId": "MHS",
            "pollControlId": "TEMP.TEST.PICKUP.835.4COMBINE",
            "serviceAreaId": "MMC"
        },
        "initialProps": "RouteList=combine.CombineX12~StagingDir=/edibatch/edidev/TEST_PICKUP/4combine/Oxford~AlertOnZeroFiles=Y",
        "pollControlDescr": "Test Pickup 835 files to combine",
        "pollLogs": null,
        "processName": "Montefiore Remittance",
        "processReceiver": "HB-EPIC",
        "processSender": "Test",
        "processTransType": "835",
        "stepMask": "1",
        "stepNo": "1",
        "systemId": "EAGLE"
    }
]
