module.exports = [
    "ALL",
    "HSR",
    "MEDITECH",
    "ZOTEC",
    "EHUB",
    "HOMEHEALTH",
    "MCKESSON",
    "HUB",
    "SATP",
    "EAGLE",
    "DOSA",
    "HB-EPIC",
    "CERC",
    "MOT",
    "OTHER",
    "Epic White Plains-SMG-EHUB",
    "HH-EPIC",
    "Epic White Plains-SMG",
    "HB-EHUB",
    "FPP",
    "OBGYN",
    "PB-EPIC",
    "MCKESSON2"
]
